# Application Properties
spring:
  application:
    name: Liquibase Demo
  # Jpa Properties
  datasource:
    #url: jdbc:mysql://localhost:3306/liquibasedemo?serverTimezone=UTC
    url: jdbc:oracle:thin:@url:1521:service
    username: root
    password: 123

  jpa:
    hibernate:
      ddl-auto: none
    hbm2ddl:
      auto: none

  # Liquibase properties
  devtools:
    restart:
      enabled: true
  liquibase:
    contexts: dev
    change-log: classpath:db/db.changelog-master.xml

## Server Properties
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: ["health","info"]
  endpoint:
    auditevents:
      enabled: true

